// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInUserRequest) Reset()         { *m = SignInUserRequest{} }
func (m *SignInUserRequest) String() string { return proto.CompactTextString(m) }
func (*SignInUserRequest) ProtoMessage()    {}
func (*SignInUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SignInUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInUserRequest.Unmarshal(m, b)
}
func (m *SignInUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInUserRequest.Marshal(b, m, deterministic)
}
func (m *SignInUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInUserRequest.Merge(m, src)
}
func (m *SignInUserRequest) XXX_Size() int {
	return xxx_messageInfo_SignInUserRequest.Size(m)
}
func (m *SignInUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInUserRequest proto.InternalMessageInfo

func (m *SignInUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInUserResponse) Reset()         { *m = SignInUserResponse{} }
func (m *SignInUserResponse) String() string { return proto.CompactTextString(m) }
func (*SignInUserResponse) ProtoMessage()    {}
func (*SignInUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *SignInUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInUserResponse.Unmarshal(m, b)
}
func (m *SignInUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInUserResponse.Marshal(b, m, deterministic)
}
func (m *SignInUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInUserResponse.Merge(m, src)
}
func (m *SignInUserResponse) XXX_Size() int {
	return xxx_messageInfo_SignInUserResponse.Size(m)
}
func (m *SignInUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInUserResponse proto.InternalMessageInfo

func (m *SignInUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*SignInUserRequest)(nil), "user_service.SignInUserRequest")
	proto.RegisterType((*SignInUserResponse)(nil), "user_service.SignInUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xb1, 0xe3, 0x8b, 0x53, 0x8b, 0xca, 0x32,
	0x93, 0x53, 0x95, 0xbc, 0xb9, 0x04, 0x83, 0x33, 0xd3, 0xf3, 0x3c, 0xf3, 0x42, 0x8b, 0x53, 0x8b,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0x8a, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x90, 0x5c, 0x41, 0x62, 0x71, 0x71,
	0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x44, 0x0e, 0xc6, 0x57, 0x52, 0xe1, 0x12, 0x42, 0x36, 0xac,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0x6a, 0x0e, 0x53, 0x66,
	0x8a, 0x93, 0x78, 0x94, 0x68, 0x7a, 0x6a, 0x1e, 0xd8, 0x31, 0xfa, 0xc8, 0x6e, 0x49, 0x62, 0x03,
	0x8b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd5, 0x1a, 0xd8, 0xae, 0x00, 0x00, 0x00,
}
